#!/usr/bin/env bash

xrandr --output DP-0 --mode 1920x1080 --left-of eDP-1-1 --rate 144.00 --output HDMI-0 --mode 2560x1440 --left-of DP-0 --rate 144.00 --primary
#
# xrandr --output HDMI-0 mode 3840x2160 --left-of eDP-1-1 --rate 60.00 --primary
