#!/usr/bin/bash

set -e

nvim_install() {
	curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
	sudo rm -rf /opt/nvim
	sudo tar -C /opt -xzf nvim-linux-x86_64.tar.gz
}

# TODO: this is supposed to come from config = maybe I should vim configs as submodule
# git clone git@github.com:meliodas0n/astrovim ~/.config/nvim
# nvim
