#!/usr/bin/bash

tmux_install() {
  echo "installing tmux and tpm"
  sudo apt-get install tmux -y
  rm -rf $HOME/.tmux/plugins/tpm
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  cp $(dirname $0)/install/.tmux.conf ~/
  echo "installation completed"
}

tmux_install
