[window]
padding = { x = 5, y = 5 }
decorations = "none"

[font]
normal = { family = "SpaceMono Nerd Font", style = "Regular" }
size = 12

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[cursor.style]
shape = "Beam"
blinking = "On"